### ISSUE TITLE
Remove license section from Readme

### ISSUE THREAD

**Issue by sunnybeta** [icecreamtheme/xresources#2]
# Reason

This already exists as a feature of GitHub at the top of the `README` and is not needed within the README

**Comment by jbrown307** [comment]
Hi sunnybeta, I would like to help but I'm new to this whole open source thing : ) Should I just submit the pull request to you or should this issue be assigned to me first? Thanks

**Comment by sunnybeta** [comment]
Hi @jbrown307. You can simply submit a pull request here. I will assign it to you in any case. This is a just a pet project. Nothing serious here.
